<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>

<%@include file="includes/cachecheck.jsp"%>
<%@page import="java.sql.*"%>
<%@include file="includes/SessionValidation.jsp"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Robocode</title>
<%@include file="includes/header.jsp"%>
<script src="http://code.jquery.com/jquery.min.js"></script>
</head>
<BODY>
<div style="position:absolute; left:1250px;top:60px;"><a href="welcome.jsp">back to main</a></div>
<div style="position:absolute; left:300px;top:50px;">
<P>
<BR><BR>
<CENTER><U><B>


Contributors of the SAAS ON PAAS system
</CENTER></U></B><BR><BR>


This system is the academic project of <B>THE UNIVERSITY OF TEXAS AT DALLAS(UTD)</B>. This project comes under the subject CLOUD COMPUTING.
<BR><BR>
This system guided by the Prof <B>Dr. I ling Yen</B> ,Professor at UTD
<BR><BR>
This system also guided by <B>Nidhi Solanki</B>, Teaching Assistant,UTD
<BR><BR>
The system was generated by group of six peoples who are all graduate student of the UTD. The members are
<BR><B>
*Divakaran Jeyachandran<BR>
*Ganesh Kumar<BR>
*Gayathri Srirangam Seshadri<BR>
*Sriram Kumar<BR>
*Srivatsan Varadarajan<BR>
*Vignesh Duraisamy<BR>

</B>
<BR>
The copy right of the system goes above eight members.
</div>
</BODY>
<%@include file="includes/fotter.jsp"%>
</html>